services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 1s
      timeout: 5s
      retries: 30  # dajemy więcej czasu na gotowość
      start_period: 10s
    networks:
      - backend
  app:
    build: 
      context: .
    command: ["uvicorn", "presentation.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    container_name: notepad_app


  self_delete:
    build: 
      context: .
    command: ["python", "scripts/self_delete_worker.py"]
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    container_name: notepad_self_delete
    restart: on-failure
    

networks:
  backend:
#define volume for persistent database storage
volumes:
  db_volume: 